In [1]:
!pip install transformers sentencepiece accelerate openpyxl -q

In [2]:
import pandas as pd

df = pd.read_excel("/content/baseline_379_results.xlsx")

print("Rows:", len(df))
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '/content/baseline_379_results.xlsx'

In [3]:
import os

for root, dirs, files in os.walk("/"):
    for f in files:
        if "baseline" in f and f.endswith(".xlsx"):
            print(os.path.join(root, f))

/baseline_379_results.xlsx

In [4]:
df = pd.read_excel("PASTE_THE_PRINTED_PATH_HERE")
print("Rows:", len(df))
df.head()

FileNotFoundError: [Errno 2] No such file or directory: 'PASTE_THE_PRINTED_PATH_HERE'

In [5]:
import pandas as pd

df = pd.read_excel("/baseline_379_results.xlsx")

print("Rows:", len(df))
df.head()

Rows: 379

,id,prompt,normal_text,watermarked_text,normal_z_score,normal_green_fraction,normal_prediction,watermarked_z_score,watermarked_green_fraction,watermarked_prediction
0,0,Explain artificial intelligence in simple terms.,Explain artificial intelligence in simple term...,Explain artificial intelligence in simple term...,1.715834,0.309677,False,10.248630,0.606452,True
1,1,Describe why artificial intelligence is import...,Describe why artificial intelligence is import...,Describe why artificial intelligence is import...,-0.510113,0.232258,False,12.289081,0.677419,True
2,2,Give a beginner-friendly overview of artificia...,Give a beginner-friendly overview of artificia...,Give a beginner-friendly overview of artificia...,2.349956,0.331210,False,11.381159,0.643312,True
3,3,Explain the main benefits and risks of artific...,Explain the main benefits and risks of artific...,Explain the main benefits and risks of artific...,0.826767,0.278481,False,0.000000,0.250000,False
4,4,Describe how artificial intelligence affects e...,Describe how artificial intelligence affects e...,Describe how artificial intelligence affects e...,-0.739600,0.224359,False,13.867505,0.730769,True

In [6]:
!pip install transformers sentencepiece accelerate openpyxl -q

In [7]:
import pandas as pd

df = pd.read_excel("/baseline_379_results.xlsx")

print("Rows:", len(df))
df.head()

Rows: 379

,id,prompt,normal_text,watermarked_text,normal_z_score,normal_green_fraction,normal_prediction,watermarked_z_score,watermarked_green_fraction,watermarked_prediction
0,0,Explain artificial intelligence in simple terms.,Explain artificial intelligence in simple term...,Explain artificial intelligence in simple term...,1.715834,0.309677,False,10.248630,0.606452,True
1,1,Describe why artificial intelligence is import...,Describe why artificial intelligence is import...,Describe why artificial intelligence is import...,-0.510113,0.232258,False,12.289081,0.677419,True
2,2,Give a beginner-friendly overview of artificia...,Give a beginner-friendly overview of artificia...,Give a beginner-friendly overview of artificia...,2.349956,0.331210,False,11.381159,0.643312,True
3,3,Explain the main benefits and risks of artific...,Explain the main benefits and risks of artific...,Explain the main benefits and risks of artific...,0.826767,0.278481,False,0.000000,0.250000,False
4,4,Describe how artificial intelligence affects e...,Describe how artificial intelligence affects e...,Describe how artificial intelligence affects e...,-0.739600,0.224359,False,13.867505,0.730769,True

In [8]:
from transformers import AutoTokenizer, AutoModelForSeq2SeqLM
import torch

device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

para_model_name = "Vamsi/T5_Paraphrase_Paws"

para_tokenizer = AutoTokenizer.from_pretrained(para_model_name)
para_model = AutoModelForSeq2SeqLM.from_pretrained(para_model_name).to(device)
para_model.eval()

print("Paraphrase model loaded.")

Device: cpu

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:124: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

config.json:   0%|          | 0.00/1.21k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

spiece.model:   0%|          | 0.00/792k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/1.79k [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/892M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/257 [00:00<?, ?it/s]

Paraphrase model loaded.

In [10]:
def paraphrase_text(text, seed=123):
    prompt = "paraphrase: " + str(text) + " </s>"

    inputs = para_tokenizer(
        prompt,
        return_tensors="pt",
        truncation=True,
        max_length=512
    ).to(device)

    torch.manual_seed(seed)

    outputs = para_model.generate(
        **inputs,
        max_length=256,
        do_sample=True,
        top_k=120,
        top_p=0.95,
        temperature=1.4,
        num_return_sequences=1
    )

    return para_tokenizer.decode(outputs[0], skip_special_tokens=True)

In [11]:
sample_text = df.loc[0, "watermarked_text"]

print("ORIGINAL:")
print(sample_text[:1000])

print("\nPARAPHRASED:")
print(paraphrase_text(sample_text, seed=999))

ORIGINAL:
Explain artificial intelligence in simple terms.

To understand how this will work, let's assume a person is a person who can solve a problem and can understand it better. One person might understand the problem better than the other and would be able to understand it better, and there might be a problem in the relationship that will lead to that.

Consider that person and the relationship could be different. Would that person be able to understand that person better and understand it better in the relationship? Would the person be able to understand that relationship better in the relationship? For example, might a person understand better that he was in the relationship and understand better with that person than with the person who understands that relationship better? Would the person in the relationship be able to understand that relationship better in

PARAPHRASED:
So to understand how this works, let's suppose a person can solve a problem and understand it better. I could understand that person better to understand the problem and better understand it in the relationship? Wther a person in the relationship understand the better of the relationship than the person whom he understands better that relationship ?

In [12]:
!git clone https://github.com/jwkirchenbauer/lm-watermarking
%cd lm-watermarking
!pip install -r requirements.txt -q

Cloning into 'lm-watermarking'...
remote: Enumerating objects: 351, done.
remote: Counting objects: 100% (57/57), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 351 (delta 32), reused 16 (delta 16), pack-reused 294 (from 2)
Receiving objects: 100% (351/351), 12.01 MiB | 16.48 MiB/s, done.
Resolving deltas: 100% (108/108), done.
/content/lm-watermarking

In [13]:
from transformers import AutoTokenizer
from extended_watermark_processor import WatermarkDetector

detector_tokenizer = AutoTokenizer.from_pretrained("gpt2")
vocab = list(detector_tokenizer.get_vocab().values())

gamma = 0.25
z_threshold = 4.0

detector = WatermarkDetector(
    vocab=vocab,
    gamma=gamma,
    seeding_scheme="selfhash",
    device=device,
    tokenizer=detector_tokenizer,
    z_threshold=z_threshold,
    normalizers=[],
    ignore_repeated_ngrams=False,
    select_green_tokens=True
)

print("Detector ready.")

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

Detector ready.

In [14]:
original_detection = detector.detect(sample_text)
paraphrased = paraphrase_text(sample_text, seed=999)
paraphrase_detection = detector.detect(paraphrased)

print("Before z-score:", original_detection["z_score"])
print("Before prediction:", original_detection["prediction"])

print("After z-score:", paraphrase_detection["z_score"])
print("After prediction:", paraphrase_detection["prediction"])

Before z-score: 10.24862959629972
Before prediction: True
After z-score: 4.5850407708172565
After prediction: True

In [15]:
attack_results = []

for i in range(len(df)):

    if i % 10 == 0:
        print(f"Running {i+1}/{len(df)}")

    original = df.loc[i, "watermarked_text"]

    before = detector.detect(original)

    paraphrased = paraphrase_text(original, seed=123+i)

    after = detector.detect(paraphrased)

    attack_results.append({
        "id": i,
        "prompt": df.loc[i, "prompt"],
        "before_z_score": before["z_score"],
        "after_z_score": after["z_score"],
        "z_score_drop": before["z_score"]-after["z_score"],
        "before_prediction": before["prediction"],
        "after_prediction": after["prediction"],
        "original_text": original,
        "paraphrased_text": paraphrased
    })

Running 1/379
Running 11/379
Running 21/379
Running 31/379
Running 41/379
Running 51/379
Running 61/379
Running 71/379
Running 81/379
Running 91/379
Running 101/379
Running 111/379
Running 121/379
Running 131/379
Running 141/379
Running 151/379
Running 161/379
Running 171/379
Running 181/379
Running 191/379
Running 201/379
Running 211/379
Running 221/379
Running 231/379
Running 241/379
Running 251/379
Running 261/379
Running 271/379
Running 281/379
Running 291/379
Running 301/379
Running 311/379
Running 321/379
Running 331/379
Running 341/379
Running 351/379
Running 361/379
Running 371/379

In [16]:
attack_df = pd.DataFrame(attack_results)

print("Before detection rate:", attack_df["before_prediction"].mean())
print("After detection rate:", attack_df["after_prediction"].mean())

print("Average z-score before:", attack_df["before_z_score"].mean())
print("Average z-score after:", attack_df["after_z_score"].mean())

print("Average z-score drop:", attack_df["z_score_drop"].mean())

Before detection rate: 0.978891820580475
After detection rate: 0.525065963060686
Average z-score before: 10.359823317029909
Average z-score after: 4.151035707042534
Average z-score drop: 6.208787609987375

In [17]:
attack_df.to_excel("experiment2_paraphrasing_results.xlsx", index=False)

In [18]:
from google.colab import files
files.download("experiment2_paraphrasing_results.xlsx")